Amazon locations example
CartoDB/deck.gl-examples pull request #2
Opened 2023-11-08 22:18 UTC by menusal

## Description

Replicate the following example: [codesandbox](https://codesandbox.io/s/carto-deck-gl-examples-rimo9x?from-embed=&initialpath=/styling/proportional-symbol-map.html&file=/styling/proportional-symbol-map.html) in Amazon locations

<img width="1440" alt="image" src="https://github.com/CartoDB/deck.gl-examples/assets/5357085/9daf29bc-9284-40ed-8dd8-7dc99737cea3">

Bonus: add a slider control to filter by population
Interactivity as hover is required to show the name + pop

Shorcut: [sc-361050](https://app.shortcut.com/cartoteam/story/361050/basemaps-basic-hello-world)

## CHECKLIST

- [x] Amazon locations base map
- [x] Tooltip
- [x] Slider to filter by population

## TODO

- Update attribution info
- Basemap selector

2023-11-09 12:59 UTC, alasarr requested changes

2023-11-09 12:59 UTC, alasarr commented on amazon-locations/package.json
> +  "name": "carto-deckgl-example-basemaps",
amazon-basemap

2023-11-09 12:59 UTC, alasarr commented on amazon-locations/.env
> +VITE_API_CONNECTION_NAME=bqconn2
Apply same things than https://github.com/CartoDB/deck.gl-examples/pull/1

2023-11-09 12:59 UTC, alasarr commented on amazon-locations/index.ts
> +  if (!selectedPopulationSelector || !populationLabel) {
populationLabel is not used

2023-11-09 12:59 UTC, alasarr commented on amazon-locations/index.ts
> +  map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "bottom-right");
Remove it to stay homogeneous with the rest of examples

2023-11-09 22:31 UTC, menusal commented on amazon-locations/package.json
> +  "name": "carto-deckgl-example-basemaps",
Done

2023-11-09 22:39 UTC, menusal commented on amazon-locations/index.ts
> +const SQL_QUERY = `
Done

2023-11-09 22:41 UTC, menusal commented on amazon-locations/index.ts
> +const getColorConfiguration = () => colorCategories({
Done

2023-11-21 18:56 UTC, alasarr approved these changes

2023-11-21 18:56 UTC, alasarr commented on amazon-locations/package.json
> +  "name": "carto-deckgl-amazon-locations-example",
```suggestion
  "name": "carto-deckgl-amazon-locations",
```

2023-11-22 09:09 UTC, merged